blank_issues_enabled: true
contact_links:
  - name: Ask a question or get support
    url: https://join.slack.com/t/nixtlacommunity/shared_invite/zt-1pmhan9j5-F54XR20edHk0UtYAPcW4KQ
    about: Ask a question in the Nixtla community Slack.
